<a href="https://colab.research.google.com/github/kkknewbie9/Complete-Python-3-Bootcamp/blob/master/Day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Implementing Numpy using python programming**


In [4]:
#importing libraries

import numpy as np

a = [1,2,3,4]  #list

#list to array

arr1 = np.array(a)
print(arr1)

b = [[1,2,3,4],[4,5,6,7]]  #list2
arr2 = np.array(b)

print(arr2)

[1 2 3 4]
[[1 2 3 4]
 [4 5 6 7]]


In [24]:
#range of variable

import sys

s = np.arange(10000)

print("size of each element of numpy array in bytes", s.itemsize)
print("size of whole array in bytes", s.size * s.itemsize)

size of each element of numpy array in bytes 8
size of whole array in bytes 80000


In [6]:
import numpy as np
import time

a = range(10000)
b = range(10000)

start = time.time() #marks the start time

# list comprehension (mul each ele of a and b)

ab = [(a*b) for a,b in zip(a,b)]

end = time.time()  #mark the end time
print("Total time taken:", end - start)

Total time taken: 0.002521514892578125


In [7]:
import numpy as np

arr3 = np.array([[1,2,3],[4,5,6]], ndmin = 2)  #2D np array

print(arr3)


[[1 2 3]
 [4 5 6]]


In [10]:
arr4 = np.array([[1,2,3],[4,5,6]])

print(arr4.dtype)
print(arr4.ndim)
print(arr4.shape)
print(arr4.size)

int64
2
(2, 3)
6


In [11]:
#creating 2X2 matrix with 0s

zero1 = np.zeros((2,2))
print(zero1)

[[0. 0.]
 [0. 0.]]


In [13]:
c = np.arange(3,10,2)

print(type(c))

<class 'numpy.ndarray'>


In [14]:
a = [1,2,3,4,5]

b = np.array(a)
print(b)


[1 2 3 4 5]


In [16]:
#slicing - creating substrings from the main string; dividing the elements in the list
# indexing - getting the value from a specific index position or from lower to upper range
# range(lower,upper+1)  --> array[lower:upper+1]

# negative indexing
b[-1]
b[-3]


3

In [17]:
#print from index 0 to 2

b[0:3]

array([1, 2, 3])

In [18]:
#updating values

b[0] = 10

print(b)

[10  2  3  4  5]


In [20]:
#all elements from index 2 

print(b[2:])

print(b[:3])

[3 4 5]
[10  2  3]


In [21]:
c = np.array([[1,2,3,4,5],[6,7,8,9,10]])
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [23]:
print(c[0][0])

1


# **Pandas Library implementation**

In [ ]:
# pandas  - handle data and dataset

import pandas as pd
dataset = 

# tail, shape, head, dtype
#check info of data --> dataset.info()
#description of dataset --> dataset.describe()


In [27]:
import pandas as pd

dataset1 = pd.read_html('https://en.wikipedia.org/wiki/Data_science')[0]
dataset1.head()

0
0                                Part of a series on
1                    Machine learningand data mining
2  Problems Classification Clustering Regression ...
3  Supervised learning.mw-parser-output .nobold{f...
4  Clustering BIRCH CURE Hierarchical k-means Exp...

In [ ]:
# dataset.Age
# dataset.EstimatedSalary
# dataset(['age', 'estsalary', 'purchased'])